name: 'Configuration Normalizer'
type: module
description: 'Normalizes configuration for comparison.'
core: 8.x
core_version_requirement: ^8 || ^9
package: Config
dependencies:
  - config_filter:config_filter

# Information added by Drupal.org packaging script on 2020-05-29
version: '8.x-1.0-alpha6'
project: 'config_normalizer'
datestamp: 1590768710
