name: 'Configuration Synchronizer'
type: module
description: 'Synchronize your site with updated configuration provided by modules and themes.'
core_version_requirement: ^8.8 || ^9
package: Config
configure: config_distro.import
dependencies:
  - 'config_distro:config_distro_filter (>=8.x-1.0-alpha4)'
  - config_merge:config_merge
  - config_normalizer:config_normalizer
  - 'config_provider:config_provider (>=8.x-2.x)'
  - config_snapshot:config_snapshot
  - config_update:config_update

# Information added by Drupal.org packaging script on 2020-07-07
version: '8.x-2.0-beta7'
project: 'config_sync'
datestamp: 1594083317
